language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew :skygear:test --info

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    repo: SkygearIO/skygear-SDK-Android
    tags: true

env:
  global:
    - BINTRAY_USER="skygeario-builder"
    # BINTRAY_API_KEY
    - secure: "AA1JqW1GST/LEaaRCfdYmBPvMfoutSzSQlXOzTDOK/gccatphpW2vqf3KbA7ukDKpSwiIAVn4yttV/5MVQ8corvHXF5Vz5SqYfjM/g92JaKdP6DA4q5sAWzP86JhRqbuD12Vi9JvxlWbAWGcAF6CfMuXIeL09XdA0BQwm0D29+RyGkfv/Lit2aTBIcUWbhnOI3VF22lqwi9iwoJvMXkTzNcXQNSpViLjYhnsI/s0GFdqV45kLwY7ZeWzODG76sVJov9cIIegD8PKdO/wtO5HXBbDqsCC1GYSRQ7YmW1ec8VFBSghdb0IuQzh7mcCIauD0jTeRg4Kgz8Kj7sHvgrd4JUSv0kROSq+ANY0oX5W+S/WnvuT/IqluPCzfmDcv0Quyw4w2vSG/G8aVqXkX5eASbV9p4dMCnuM+PDdvQSKEA/jRCU0PatMRh30G3LdLn8NuNue8KBox36VTpZNYj0eIaoU8Sbab92iWnnEGS/LiAu1Th/dCSXHcKlRkOgI2GeggLnntOzqK/6VDhyrIyo9tWcNXRBNzWaqITPuER3Ryd2I218doPrOlDQAh+cOX1t7j8BPZTFeFRuEbLBcIQmN9IhjnczI6yBL7C0jLWu1RLOS9AQgcyV3CnpTBr5enBxCaLzJoUH4mDU4sEqdjtwnE996n87XI5HAF9DZNPhZSZw="

notifications:
  slack:
    secure: "boKBSUo8wZLXMAAzRGfu3IXeoIDvpzWHDDQoV2jDPcGxbNOApxE9F2dvTWhyqBwquqbZ1gMHorpW9hiATAQaacT+e6hUrHegXbpQijGQJ4yc1UW47VKxnDU+Jdf3fVY9TRymdqMvR2IoB9XVqJU12ISFKNIpNVChw1LZvEIhj6QTkOCUUokBS04Jvti8sxIK0MQ3epUTyVNMs90RAd+S0aVdZHHXQOaH8pFciPCrKNE1MPTNQRb6sZ9GFi3ZqmLxlUTKBdoe2knNq+aVxNcYq9yl27QxknggG0u9nNAQdsqnAN/AGOYfNz5gF0zsfQFVT7D3zpuYdDbtdNMDsh9cIru4KkIShDVVkwppyt3jRgWKIRdwfYS4qJfbYl35Xjyswg2UJjoZSrgatMxNXJCvrlC1aIWK2YeB45+gctVwzvHmokCzV0kZpgJB5GWmY6qcI1VKCUIUt59jCMqKLJJixmmBnagaPcAaY6V70WoaRT4dF+0Xxb0ehMrtuFMdxFeir7ULfu2R4VfLd7GpZSXBDybGnYUZWv3HydN9D/QAvGgUUSevXrLryLQJNePFVrqkU66oBGqj0Ney7VKq4UB0b4b5sxFpkF56qo43tPEPU4qlrOw1wpeIx0xNSm8w3XTNs7Fd1mA585UhAcDS7XowhtRJpQrEA3Km4fYXrUtL9KA="
